title: Sharpred
email: paul@sharpred.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site for Paul Ryan.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: sharpred
github_username:  sharpred

# Build settings
markdown: kramdown
theme: minima
# from https://jekyllrb.com/docs/continuous-integration/
exclude: [vendor, gcp, google575963d4adf7f984.html]
# from http://jmcglone.com/guides/github-pages/
#permalink: /blog/:year/:month/:day/:title