title: Sharpred
email: paul@sharpred.com
description: > # this means to ignore newlines until "baseurl:"
  Paul Ryan, Mobile App Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sharpred.com" # the base hostname & protocol for your site
twitter_username: sharpred
github_username:  sharpred

# Build settings
markdown: kramdown
theme: minima
# from https://jekyllrb.com/docs/continuous-integration/
exclude: [vendor, gcp, google575963d4adf7f984.html]

# Google services
google_analytics: UA-179410290-1
