name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  buildandhtmlproof:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: install prerequisites
      run: gem install minima jekyll html-proofer
    
    - name: jekyll build
      run: bundle exec jekyll build
    
    - name: html proofer
      run: bundle exec htmlproofer --url-ignore "http://localhost:8153/go" ./_site 
    

    
